# Generated by Django 3.2.6 on 2021-08-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('birth_name', models.CharField(max_length=120)),
                ('quirk', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('location', models.CharField(max_length=120)),
                ('villain_vigilante', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
