# Generated by Django 3.2.6 on 2021-08-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='rank',
            field=models.CharField(max_length=120),
        ),
    ]
