# Generated by Django 3.2.6 on 2021-09-10 18:45

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='images',
            field=models.ImageField(default=1, upload_to=members.models.upload_to),
            preserve_default=False,
        ),
    ]
