# Generated by Django 3.2.9 on 2021-12-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='url_image',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
