# Generated by Django 3.2.9 on 2021-12-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_members_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='url_image',
            field=models.CharField(max_length=800),
        ),
    ]
